language: node_js
node_js:
  - "10"
  - "12"
  - "14"
  - "node"
env:
  - WEBPACK_VERSION=4.4 DEVSERVER_VERSION=3.0
  - WEBPACK_VERSION=latest DEVSERVER_VERSION=latest
matrix:
  fast_finish: true
cache:
  directories:
    - "$HOME/.npm"
before_install:
  - npm install -g npm@latest
  - npm --version
install:
  - npm install -g codecov
  - npm ci
  - npm install webpack@$WEBPACK_VERSION webpack-dev-server@$DEVSERVER_VERSION
script:
  - npm test
  - npm run lcov
  - codecov
